apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "extensible-secrets-generator.fullname" . }}-manager-role
  labels:
  {{- include "extensible-secrets-generator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.esg.jkulzer.dev
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.esg.jkulzer.dev
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "extensible-secrets-generator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: extensible-secrets-generator
    app.kubernetes.io/part-of: extensible-secrets-generator
  {{- include "extensible-secrets-generator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "extensible-secrets-generator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "extensible-secrets-generator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'