apiVersion: v1
kind: Service
metadata:
  name: {{ include "extensible-secrets-generator.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: extensible-secrets-generator
    app.kubernetes.io/part-of: extensible-secrets-generator
    control-plane: controller-manager
  {{- include "extensible-secrets-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "extensible-secrets-generator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}