apiVersion: secrets.esg.jkulzer.dev/v1alpha1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: secret-sample
    app.kubernetes.io/part-of: extensible-secrets-generator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: extensible-secrets-generator
  name: secret-sample
spec:
  # TODO(user): Add fields here
