name: Build operator container image
on: [push]
  # push:
    # tags:
    #   - "*" # Only runs on pushes with a tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0

