name: Build operator container image
on: [push]
  # push:
    # tags:
    #   - "*" # Only runs on pushes with a tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: xunholy/operator-sdk-action@v1.0.0
      with:
        image: "extensible-secrets-generator"
        dirPath: "${{ github.workspace }}./Dockerfile"
